from typing import Literal

DEBUG = False
VERSION_TYPE: Literal["global", "brazilian"] = "global"
VERSION_NUMBER = "3.4.0"
TOAST_HISTORY = {}

names = {"global": "RokNet", "brazilian": "ROKBOT"}

BOT_NAME: Literal["RokNet", "ROKBOT"] = names[VERSION_TYPE]

ownerid = "7oofxdj8uH"

global_name = "Rokbd"
global_secret = "a968396e3fdfff2a2eaf14516fb283b7b7013e19cf392c863c90e0d8c41d9be0"

VERSION_TYPE_name = "RokbdBR"
VERSION_TYPE_secret = "6d15b7ee5e7312238105efd4b648535835dc1ce5f4250fe2dc82910db43147b6"

SUPABASE_URL: str = "https://rytpbbadrdnfozckfjde.supabase.co"
SUPABASE_KEY: str = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5dHBiYmFkcmRuZm96Y2tmamRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDUxNDU2ODAsImV4cCI6MjAyMDcyMTY4MH0.K3da9dT4qw9e3osKrQakBEPVjeLWMDo0dEdytVLLqfY"
)

default_worker_settings = {"loop_task": True, "waiting_cooldown": [60, 90], "close_emulator": True}

default_dic = {
    "instance": "",
    "name": "",
    "host": "127.0.0.1",
    "port": 0,
    "API_KEY": "",
    "loop_task": False,
    "time_to_wait_loop1": 60,
    "time_to_wait_loop2": 110,
    "leave_game_loop": True,
    "scheduler": False,
    "schedules": {},
    "emulator": "",
}

default_profile = {
    "timing": [],
    "enable_timing": False,
    "enabled": False,
    "kingdom": 0,
    "city_x": 0,
    "city_y": 0,
    "radius": 30,
    "First": "stone",
    "Second": "food",
    "Third": "gold",
    "Fourth": "wood",
    "Fifth": "food",
    "Sixth": "food",
    "Seventh": "food",
    "First_level": 5,
    "Second_level": 5,
    "Third_level": 5,
    "Fourth_level": 5,
    "Fifth_level": 5,
    "Sixth_level": 4,
    "Seventh_level": 4,
    "rss_custom_preset": False,
    "auto_reconnect": True,
    "auto_captcha": True,
    "check_donation": False,
    "gather_alliance_pit": False,
    "use_enhanced_buff": False,
    "gather_rss": False,
    "buy_merchant": False,
    "claim_daily_quests": False,
    "collect_ressource": False,
    "defeat_barbarians": False,
    "barbarians_level": 25,
    "barbarians_preset": {
        "1": False,
        "2": False,
        "3": False,
        "4": False,
        "5": False,
        "6": False,
        "7": False,
    },
    "claim_mails": False,
    "gather_gem_note_limit": 0,
    "restart_game": False,
    "switch_character": False,
    "leave_game_switch_character": False,
    "scout_fog": False,
    "scout_duration1": 60,
    "scout_duration2": 90,
    "slow_mode": False,
    "sleep_multiplicator": 1,
    "auto_log_back": True,
    "log_back1": 5,
    "log_back2": 10,
    "claim_daily_vip": False,
    "claim_daily_chest": False,
    "claim_campaign": False,
    "start_fort": False,
    "rally_type": "cav",
    "rally_time": 10,
    "rally_radius": 20,
    "rally_count": 2,
    "mauraudeurs_forts": False,
    "heal_troop": False,
    "healing_building_x": 980,
    "healing_building_y": 267,
    "healing_count": 1500,
    "material_production": False,
    "material_choice_1": "leather",
    "material_choice_2": "leather",
    "material_choice_3": "leather",
    "material_choice_4": "leather",
    "material_choice_5": "leather",
    "alliance_help": False,
    "train_troops": False,
    "infantry_camp": [],
    "cavalry_camp": [],
    "archery_camp": [],
    "siege_camp": [],
    "hospital": [],
    "scout_camp": [],
    "infantry_enable": True,
    "cavalry_enable": True,
    "archery_enable": True,
    "siege_enable": True,
    "infantry_tier": "t1",
    "cavalry_tier": "t1",
    "archery_tier": "t1",
    "siege_tier": "t1",
    "city_transfer": [],
    "transfer_enable": False,
    "transfer_food": 0,
    "transfer_wood": 0,
    "transfer_stone": 0,
    "transfer_gold": 0,
    "upgrade_city": False,
    "kill_marauders": False,
    "kill_marauders_duration": [30, 90],
    "rally_skip_back": False,
    "gather_rss_method": "default",
    "fast_rss_transfer": False,
    "city_hall_position": [],
    "upgrade_city_method": "normal",
    "academic_research": False,
    "academy_position": [],
    "buy_merchant_skip": False,
    "expedition_shop_ethel": False,
    "expedition_shop_items": False,
    "gather_gem": False,
    "gem_check1": 60,
    "gem_check2": 120,
    "gem_experimental": False,
    "recenter_feature": True,
    "gather_gem_duration1": 60,
    "gather_gem_duration2": 90,
    "gather_gem_spiral_method": True,
    "gather_gem_swipe_check": True,
    "gather_gem_compare_march_duration": True,
    "gather_gem_enable_node_limit": False,
    "gather_gem_method": "map",
    "gather_gem_center_pos": [],
    "gather_gem_availability": "all",
    "gather_rss_availability": "all",
    "help_alliance_building": False,
}
